name: nekosophy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^1.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.7
  riverpod_generator: ^2.2.4
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
